### ISSUE TITLE
Abbreviations in naming scheme

### ISSUE THREAD

**Issue by pnkraemer** [probabilistic-numerics/probnum#110]
I stumbled upon this when reading the `OdeSolution` issue thread. 

Do we want to say `OdeSomething` or `ODESomething`? Do we do the same for `SDE` vs. `Sde`, e.g. `LinearSDE`? What if those abbreviations are stand-alone, i.e. in `IVP` or `SDE`? I understand that scipy does `OdeSomething` but so far I have always done `OdeSomething`. I guess it felt weird to say `Ode` as a stand-alone. This probably applies to any class that is defined through abbreviations (@nathanaelbosch we were talking about `PFOS` once---this would then perhaps turn into `Pfos`?). Not sure to which extend this applies to linear algebra, but at least in the filtsmooth/diffeq parts this is something we need to fix.

**Comment by nathanaelbosch** [comment]
Personally I much prefer `ODE` to `Ode`, `PFOS` to `Pfos`, and `ODESomething` to `OdeSomething`.

Just to clarify: In the `OdeSolution` thread I used that exact name just because Scipy uses it (https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.OdeSolution.html#scipy.integrate.OdeSolution), not as an actual suggestion for our naming. Maybe that was a bit misleading on my part.

**Comment by pnkraemer** [comment]
Cool, then we agree :) I was getting prepared for a heated argument over a really minor thing... I think `DifferentialEquations.jl`also does `ODEProblem` and who are we to argue with those guys?
