### ISSUE TITLE
transition sampling is not random

### ISSUE THREAD

**Issue by pnkraemer** [probabilistic-numerics/probnum#253]
The output of `sde.LTISDE.transition_realization` is a random variable, though samples are not random. This is some sort of bug, either in `transition_realization` or in `Normal`. The following snippet reproduces the problem.

```python
>>> import probnum.random_variables as pnrv
>>> import numpy as np
>>> import probnum.filtsmooth as pnfs
>>> rv = pnrv.Normal(np.ones(2), np.eye(2))
>>> sde = pnfs.statespace.IBM(1, 1, 1.0)
>>> sde.transition_realization(rv.mean, 0., 1.)[0].sample()
array([ 0.97238237, -0.7026813 ])
>>> sde.transition_realization(rv.mean, 0., 1.)[0].sample()
array([ 0.97238237, -0.7026813 ])
```

**Comment by nathanaelbosch** [comment]
I could not reproduce this on master:
```python
>>> import numpy as np
>>> import probnum.random_variables as pnrv
>>> import probnum.diffeq as pnde
>>> rv = pnrv.Normal(np.ones(2), np.eye(2))
>>> sde = pnde.IBM(1, 1, 1.0)
>>> sde.transition_realization(rv.mean, 0., 1.)[0].sample()
array([2.38289603, 0.73705162])
>>> sde.transition_realization(rv.mean, 0., 1.)[0].sample()
array([2.05448809, 0.24228041])
```

**Comment by nathanaelbosch** [comment]
This is reproducible now! To me it seems the `random_state` is not initialized randomly:
```python
>>> import probnum as pn
>>> pn.utils.derive_random_seed(pn.utils.as_random_state(None))
2592055699
>>> pn.utils.derive_random_seed(pn.utils.as_random_state(None))
2592055699
```
@marvinpfoertner @JonathanWenger you know more about the inner workings of our random variables, do you have any thoughts about this?

**Comment by JonathanWenger** [comment]
> The output of `sde.LTISDE.transition_realization` is a random variable, though samples are not random. This is some sort of bug, either in `transition_realization` or in `Normal`. The following snippet reproduces the problem.
> 
> ```python
> >>> import probnum.random_variables as pnrv
> >>> import numpy as np
> >>> import probnum.filtsmooth as pnfs
> >>> rv = pnrv.Normal(np.ones(2), np.eye(2))
> >>> sde = pnfs.statespace.IBM(1, 1, 1.0)
> >>> sde.transition_realization(rv.mean, 0., 1.)[0].sample()
> array([ 0.97238237, -0.7026813 ])
> >>> sde.transition_realization(rv.mean, 0., 1.)[0].sample()
> array([ 0.97238237, -0.7026813 ])
> ```

@pnkraemer This is expected behaviour if i look into the code of `transition_realization`, the Gaussian rv that is created has zero covariance and is thus deterministic. 
```python
    def transition_realization(
        self,
        real,
        start,
        stop,
        step,
        **kwargs,
    ):

        rv = pnrv.Normal(real, 0 * np.eye(len(real)))
        return linear_sde_statistics(
            rv,
            start,
            stop,
            step,
            self.driftfun,
            self.driftmatfun,
            self.dispmatfun,
        )
```

If you examine the `random_state` of the objects you get different ones:
```python
sde.transition_realization(rv.mean, 0., 1.)[0].random_state
Out[15]: RandomState(MT19937) at 0x7F6BDA2A9D40
sde.transition_realization(rv.mean, 0., 1.)[0].random_state
Out[16]: RandomState(MT19937) at 0x7F6C275CE440
sde.transition_realization(rv.mean, 0., 1.)[0].random_state
Out[17]: RandomState(MT19937) at 0x7F6BD9C8F240
```

@nathanaelbosch This is intended behaviour since `derive_random_seed()` is used to generate a new random seed for a derived random quantity (typically in RV arithmetic, e.g. `-rv, rv1+rv2`. This operation should not modify the original random seed otherwise this leads to strange bugs where the order of operations matters to what samples you obtain for the same random seed. See also #202 for an example of this.

**Comment by pnkraemer** [comment]
Thanks for looking into this. 

> @pnkraemer This is expected behaviour if i look into the code of transition_realization, the Gaussian rv that is created has zero covariance and is thus deterministic.

No it is not determinstic; only what is put **into** `linear_sde_statistics` is. But in any case, if this intended behaviour, I will try to fix the way it is used, not the way it is written (if that makes sense).

**Comment by nathanaelbosch** [comment]
@JonathanWenger As @pnkraemer pointed out the output of `sde.transition_realization` is not deterministic:
```python
>>> next_rv = sde.transition_realization(rv.mean, 0., 1.)[0]
>>> next_rv.sample()
array([ 0.97238237, -0.7026813 ])
>>> next_rv.sample()
array([0.97346173, 0.29956555])
```

> If you examine the random_state of the objects you get different ones

This is true, but then I wonder even more why they seem to provide the same "random" number:
```python
>>> next_rv1 = sde.transition_realization(rv.mean, 0., 1.)[0]
>>> next_rv1.random_state
RandomState(MT19937) at 0x7FB0543BC440
>>> next_rv2 = sde.transition_realization(rv.mean, 0., 1.)[0]
>>> next_rv2.random_state
RandomState(MT19937) at 0x7FB0543BC740
>>> next_rv1.sample()
array([ 0.97238237, -0.7026813 ])
>>> next_rv2.sample()
array([ 0.97238237, -0.7026813 ])
```

> @nathanaelbosch This is intended behaviour since derive_random_seed() is used to generate a new random seed for a derived random quantity (typically in RV arithmetic, e.g. -rv, rv1+rv2. This operation should not modify the original random seed otherwise this leads to strange bugs where the order of operations matters to what samples you obtain for the same random seed. See also #202 for an example of this. 

I did not fully understand that part, what do you mean with "original random seed" here? In our example the output should be a "freshly created" random variable, so I'm still unsure where the determinism comes from.

**Comment by JonathanWenger** [comment]
Sorry for the confusion I clearly did not investigate this very thoroughly.

To my second point, they actually do share a seed (which explains the same samples), their addresses in memory of their random_state are just different:
```python
next_rv1 = sde.transition_realization(rv.mean, 0., 1.)[0]
next_rv2 = sde.transition_realization(rv.mean, 0., 1.)[0]
np.all(next_rv1.random_state.get_state()[1] == next_rv2.random_state.get_state()[1])
Out[48]: True
```

Debugging this with a test I did not see usage of the function `derive_random_seed`, but of `pn.utils.as_random_state` which just wraps `scipy._lib._util.check_random_state`. This gets us closer to the true perpetrator:

```python
rs1 = scipy._lib._util.check_random_state(None).get_state()[1]
rs2 = scipy._lib._util.check_random_state(None).get_state()[1]
np.all(rs1 == rs2)
Out[13]: True
```
Now, this means the global random state is just copied (and left as is) whenever a random variable is created. Let's check how scipy handles this:

```python
from scipy.stats import norm
rv1 = norm()
rv2 = norm()
np.all(rv1.random_state.get_state()[1] == rv2.random_state.get_state()[1])
Out[23]: True
rv1.rvs()
Out[26]: 0.7659406717684032
rv2.rvs()
Out[27]: 1.1623631427120862
```
Comparing this to ProbNum's behaviour:

```python
from probnum.random_variables import Normal
rv1 = Normal(0, 1)
rv2 = Normal(0, 1)
np.all(rv1.random_state.get_state()[1] == rv2.random_state.get_state()[1])
Out[40]: True
rv1.sample()
Out[41]: 1.0016876555025649
rv2.sample()
Out[42]: -1.251191902711161
```
So while it is expected behaviour that they both share a reference to the `np.random` Singleton. The RNG should change its state when we sample from one of the rvs. This works in the reduced toy example, so where the heck is the bug? **I am not sure yet.**

Finally, to your question @nathanaelbosch: `derive_random_seed` avoids modifying the random state of the random variable(s) involved in the arithmetic (therefore also the global state). This is what I referred to as "original" random state. This ensures that arithmetic operations on random variables do not affect sampling behaviour. See #202 for an example of this.

**Comment by JonathanWenger** [comment]
## Potential Solutions
1. Only one global random state
2. Remove `random_state` arguments in signatures
Set `random_state` property to global random state but offer not `setter` function.
Change `derive_random_seed` method to always pass the global random state on to derived random variables.

**Comment by marvinpfoertner** [comment]
Another possibly cleaner solution would be to use NumPys `SeedSequence` to spawn one `SeedSequence` per `RandomVariable` from a global `SeedSequence` which the user can optionally overwrite per `RandomVariable`. Combinations can then be done by spawning temporary `SeedSequence` from each operand, generating random states from these, sampling an integer from each random seed and then combining these into the `entropy` of a new `SeedSequence` of the derived `RandomVariable`
