### ISSUE TITLE
Refactor tests to fit into unittest framework

### ISSUE THREAD

**Issue by JonathanWenger** [probabilistic-numerics/probnum#26]
- [x] Change all existing tests to (object-oriented) `unittest` framework
   - [x] `probability`
   - [x] `linear_operators`
   - [x] `linear_solvers`
- [x] Adjust the build script for travis to run the unittests
- [x] Check whether unittest integrates with `.coveragerc` correctly to report test coverage

**Comment by JonathanWenger** [comment]
This ties in with #21 neatly.

**Comment by pnkraemer** [comment]
Thank you so much for this! 
I find the unittest framework useful, because the tests can mirror the architecture of the implementations (apart  from the convenience functions). I'll happily help you!

What is your opinion about testing convenience functions? In my code, I only doctested the convenience functions and unittested the real implementations. For the convenience functions, it seems that the only problem would be if some inputs change which should be captured well by doctests (also, it doesnt hurt to have excessive examples in the most visible functions of each module.)

**Comment by JonathanWenger** [comment]
>     * [ ]  Adjust the build script for travis to run the unittests

We can keep `pytest` as a test runner as it also runs `unittests` and its output is a little more verbose and informative (also in the command line). Just from anecdotal experience it also seems to run the eisting tests faster.

**Comment by JonathanWenger** [comment]
Implemented by 9c9da4c15061b58e58cc042e413c745cf3b7f95a.
