### ISSUE TITLE
Write an abstract interface `ProbabilisticNumericalMethod`

### ISSUE THREAD

**Issue by JonathanWenger** [probabilistic-numerics/probnum#280]
Define in an abstract way how implementations of probabilistic numerical methods look like. This enables uniformity across methods and forces us to define what PN methods look like and are.

```python
import abc


class ProbabilisticNumericalMethod(abc.ABC):
    def __init__(
        prior: Union[RandomVariable, RandomProcess]],
        action_rule: ActionRule,
        observation_process: ObservationProcess,
        belief_update: BeliefUpdate,
        stopping_criterion: StoppingCriterion,
        hyperparam_opt: HyperparameterOptimization,
    ):
        raise NotImplementedError

    def infer_solution(
        self, problem: Problem
    ) -> Tuple[Collection[Union[RandomVariable, RandomProcess]], Dict]:
        raise NotImplementedError
```

Beyond this implementation an convenience function exists which follows the NumPy/SciPy function signatures as described in https://probnum.readthedocs.io/en/latest/development/implementing_a_probnum_method.html#Interface.

**Comment by pnkraemer** [comment]
Arent you missing a prior in the init? And I'd also argue that a belief update is what happens **inside** the solver, so I don't think this needs to be specified

**Comment by JonathanWenger** [comment]
> Arent you missing a prior in the init? And I'd also argue that a belief update is what happens **inside** the solver, so I don't think this needs to be specified

For different assumptions on the problem the belief update may be different, e.g. exact vs noisy case. In my view it is just another component of the solver in the same way the action rule or stopping criterion is. In fact I would even add another function here `observe` which takes a problem and specifies how to obtain observations from it. This process also implies a potentially different belief update.

**Comment by pnkraemer** [comment]
Sure, the update is different for each method. 

Though I am a bit concerned about making this as an attribute of the base class (especially now), which would then enforce that it needs to be used this way by all PN methods. One the one hand, because it assumes a Bayesian viewpoint on the algorithm (which is not necessarily the case; see https://link.springer.com/article/10.1007/s11222-016-9671-0); on the other hand, because it is a fairly drastic code change for all algorithms. It will be a real pain to try to adhere to this pattern everywhere, especially now (I am not sure about linalg, but updating filtsmooth and diffeq into this scheme will be a large project, and perhaps affect every single line of code). 

I, personally, would try to keep this interface rather soft, that is, only put in there what is absolutely necessary and what can actually be pinpointed to be the same component for all PN algorithms. Naturally, this can (and hopefully will) evolve over time.

How about we start small and implement this interface in a way that (i) every init gets a prior (as first argument?), and (ii) every `infer_solution` gets a problem as its first (and only?) argument. I think this should be rather simple to adhere to, while providing a common interface already. Then, once we all agree on what we think belongs in the init of a PN method, we can slowly add layer by layer. For example: after prior and problem, maybe we try to unify the treatment of the stopping-criterion (which I suppose is easier to unify than the other components). 

This way, we would nudge all the implementations into the desired direction without rewriting everything at once.
