### ISSUE TITLE
Evaluate numba for potential speedup

### ISSUE THREAD

**Issue by JonathanWenger** [probabilistic-numerics/probnum#4]
http://numba.pydata.org/

**Comment by pnkraemer** [comment]
What was the result of this evaluation?

In my opinion, numba does not seem useful to the way I am programming (at the moment). The reason is that you have to define each and every input and output type which makes it quite hard to do fairly general OOP. IN fact, it feels a bit like programming in C. But I am no expert, so please change my mind!

**Comment by JonathanWenger** [comment]
I haven't started on this yet, but my current understanding is that it can be mostly helpful for nested loops. So far I haven't had to make use of that too much.

**Comment by pnkraemer** [comment]
I see. Thank you. Most (nested) loops can and should be avoided anyway, so one should be able to get decent speed without numba. It could be interesting to construct a toy example though, let's see whether we get around to this one day :)

**Comment by pnkraemer** [comment]
I guess this can be closed or at least moved to the jax-discussion?
