### ISSUE TITLE
Code Review: Sampling

### ISSUE THREAD

**Issue by JonathanWenger** [probabilistic-numerics/probnum#50]
In the preconditioned versions of `HamiltonianMonteCarlo` and `MetropolisAdjustedLangevinAlgorithm` there is a lot of code duplication. I'd suggest having a single class which either has a preconditioner as an instantiation parameter or a `preconditioned` flag. This can then influence how `momentum` and `noise` are computed in the functions.

---
```python
    def sample_langevin(self, currstate, pwidth):
        """
        """
        noise = np.random.multivariate_normal(np.zeros(len(currstate.dfx)),
                                              np.linalg.inv(currstate.ddfx))
        prec_dyn = np.linalg.solve(currstate.ddfx, currstate.dfx)
        return currstate.x - pwidth * prec_dyn + np.sqrt(2 * pwidth) * noise
```
You can reduce the computational cost by half if you use a cholesky decomposition of the covariance `currstate.ddfx` instead of an LU decomposition via `np.linalg.inv` (essentially telling the solver that your matrix is symmetric positive definite).

---
```python
class MetropolisHastings(ABC):
    """
    Abstract Metropolis-Hastings class. Contains everything but the
    proposal kernels.
    """

    good_acc_ratio = None

    def __init__(self, logdens):
        """
        """
        if not issubclass(type(logdens), objective.Objective):
            raise TypeError("Please initialise with AutoDiff instance.")
        self.logdens = logdens
```
When checking object types it is preferred to use `isinstance(logdens)` whereas `issubclass` is used to check whether a class is a subclass of another class. I think this check is found multiple times throughout the code. Note that a `ValueError` should probably be thrown here according to Python's error definitions:
>  TypeError is thrown when an operation or function is applied _to_ an object of an inappropriate type. 
>  ValueError is thrown when a function's argument is _of_ an inappropriate type. 

Further the error message needs to be updated as `AutoDiff` doesnt exist as a class.

---
```python
    def sample_nd(self, nsamps, init_state, pwidth, **kwargs):
        """
        """
```
I think `sample` would suffice as a name. This would also match the sample functions for random variables. Also I suggest renaming `nsamps` to `size=()` to match existing code style and `numpy`.

---
I like the convenience functions in this module as they can be used directly in `sample` routines for complicated new distribution classes. 

Would it make sense to have something like an `mcmc` method or an `mh` method which has as its argument `kernel=...` which then specifies the Kernel? Its done this way in some probabilistic programming languages to my knowledge. This would also adhere to the precedent of methods like `np.optimize.minimize` and `probnum.linalg.problinsolve`. 

---
Just as a reminder we need to bring the documentation up to speed of the modules in `sampling` to make this easier.

**Comment by pnkraemer** [comment]
> In the preconditioned versions of HamiltonianMonteCarlo and MetropolisAdjustedLangevinAlgorithm there is a lot of code duplication. I'd suggest having a single class which either has a preconditioner as an instantiation parameter or a preconditioned flag. This can then influence how momentum and noise are computed in the functions.

Sure, that is a way to do it. I think it at least make sense to write that version and compare them! :) 

> You can reduce the computational cost by half if you use a cholesky decomposition of the covariance currstate.ddfx instead of an LU decomposition via np.linalg.inv (essentially telling the solver that your matrix is symmetric positive definite).

True, reading `linalg.inv` makes me think it can be done better, although I like the `inv` for readability (and numerical stability, Cholesky breaks much earlier than LU does, even for matrices that are SPD in theory like covariance kernel matrices and the "cost in half" I have never seen in reality due to the efficient low-level LU decomposition algorithms which I think scipy takes from LAPACK). I agree that it is not optimal though, so it is worth a try replacing it!

> When checking object types it is preferred to use isinstance(logdens) whereas issubclass is used to check whether a class is a subclass of another class. I think this check is found multiple times throughout the code. Note that a ValueError should probably be thrown here according to Python's error definitions: (...)

Thanks! I've never been able to find this difference between ValueError and TypeError. That is something we might encounter in other parts of the code base as well, I've put down a corresponding issue.

> Further the error message needs to be updated as AutoDiff doesnt exist as a class.

True.

> I think sample would suffice as a name. This would also match the sample functions for random variables. Also I suggest renaming nsamps to size=() to match existing code style and numpy.

Generally, yes! I used `sample_nd` and `minimise_nd ` as a reminder that initial states and stuff need to be proper arrays and that the function needs to act on arrays and so on. Turned out this was useful in enforcing the right inputs as well as keeping the code short. 
How would the  `size=()` input look? Afterall one only computes `N` states of the Markov chain so `size=1`, `size=10`, etc.? This is different to `np.random.randn(size=(10, 2))` where one can set the dimensionality of the samples, too.

> I like the convenience functions in this module as they can be used directly in sample routines for complicated new distribution classes.

Cool! I wrote them because I was way to lazy to always set up these sampler objects... I think this suggestion will be one part of one of the future discussion how to best set up a `Likelihood` class which I used for inverse problems based on ODEs (this is still in ODEFilters, so relevant as soon as the current stuff is done).

> Would it make sense to have something like an mcmc method or an mh method which has as its argument kernel=... which then specifies the Kernel? Its done this way in some probabilistic programming languages to my knowledge. This would also adhere to the precedent of methods like np.optimize.minimize and probnum.linalg.problinsolve.

Not sure. Do you mean as a convenience function on top of everything? That could be done, but would it be used? 


> Just as a reminder we need to bring the documentation up to speed of the modules in sampling to make this easier.

Yeah sure, I think when the review is over we can do a quick sprint and then its done. It is not too many modules afterall :) 

**Thank you for the review**

**Comment by pnkraemer** [comment]
I know I am responsible for putting those in in the first place, but why don't we remove MCMC methods and optimisation methods from the repo until we need them? I can store them somewhere locally and recover if needed. At the moment it is only additional code that needs to be refactored according to our continuously evolving guidelines. @JonathanWenger @nathanaelbosch

**Comment by nathanaelbosch** [comment]
If you think that this is something that does not belong in the development branch I agree. Instead of storing it "locally" I would suggest to keep it either in this repo in a branch or, because we do not want to have many branches lying around, to have a branch in your fork that contains this code.

**Comment by JonathanWenger** [comment]
Fine with me!

**Comment by pnkraemer** [comment]
What are your stance on removing the entire optim folder vs. removing only the ones that are not bayesopt (even though optim would contain zero content, no?)?

**Comment by JonathanWenger** [comment]
I would say keep the folder and `__init__.py` around so the structure and doc setup files remain (and is taken into account in potential changes). Eventually somebody (e.g. Filip) will implement some version of a probabilistic optimizer.

**Comment by nathanaelbosch** [comment]
For future reference, PR #93 removed `probnum.optim` and `probnum.prob.sampling` completely from the repo (sorry Jonathan!).

**Comment by JonathanWenger** [comment]
Closing this since all sampling code is now removed from the repo.
