### ISSUE TITLE
Add an automated code style and docstring checker to Travis

### ISSUE THREAD

**Issue by JonathanWenger** [probabilistic-numerics/probnum#66]
Use a lint tool when building the project and also check all docstrings for correct syntax.

**Comment by JonathanWenger** [comment]
Automatic code formatting (`black`, `flake8`, `pylin`, `yapf`, ...)

**Comment by nathanaelbosch** [comment]
In my personal experience with code formatters (black, flake8, yapf) I found the resulting code from black to feel most natural and be most enjoyable for reading.

I also quickly checked for integration into CI, but none of the proposed options explicitly explain how to integrate with Travis-CI. Instead they provide explanations for "Github actions" (e.g. https://github.com/psf/black#github-actions). Would that also be a sufficient approach to automatically ensure a common code style?

**Comment by nathanaelbosch** [comment]
Another relevant aspect we should follow when migrating existing code is to maintain a proper git blame history, e.g. as explained here (again for black, but the general idea applies independently of which style we chose):
https://github.com/psf/black#migrating-your-code-style-without-ruining-git-blame

**Comment by nathanaelbosch** [comment]
To proceed here and get a common code style + automation set up, I see the following, roughly chronological steps:
- [ ] **Decide on a specific code style**
  I have the impression that most people either had no strong opinion on the exact tool, or suggested to use [black](https://github.com/psf/black/). I would therefore suggest that we just go with black. Regarding custom settings (e.g. the line length) I would suggest to stick to black's default settings at first, which already relaxes our current style a bit. We could change those settings easily at a later point in the future if necessary. 
  @JonathanWenger @pnkraemer opinions?
- [ ] **Port our codebase to the new, agreed-on style**
  I suggest doing this as soon as we merge `diffeq` into `development`. Black provides an [explanation on how to migrate code while keeping git blame](https://github.com/psf/black#migrating-your-code-style-without-ruining-git-blame).
  Other changes include mentions of black in our documentation and adaptations to / addition of config files for black, pre-commit, and GitHub actions. 
- [ ] **(Optional/Personal) Change local editor settings**
  This is not necessary, but I would still strongly suggest that we developers change the settings in our preferred IDE to the agreed-upon style, just to make the procedure more pleasant. This way, the code you see on GitHub is the code you last saw in your editor.
- [ ] **Automation with GitHub Actions**
  An explanation on how to set it up is provided [here](https://github.com/psf/black#github-actions). To my understanding, this should lead to automated code formatting at any push and pull request. This also seems to be before Travis-CI gets applied, such that any errors black could introduce should be caught.
- [ ] **(Maybe) Additional automation with pre-commit**
  Following [this suggestion](https://github.com/psf/black#version-control-integration) in the black README. To my current understanding, using pre-commit would apply black locally at each commit, complementing the GitHub Actions set up mentioned above. Using this is not strictly necessary for any developer, but it might improve the experience by applying code formatting at each commit instead of only once per push/PR and provides an alternative to setting up an IDE. In any case, I don't really see a disadvantage nor much additional work for setting this up and including the one config file for it.

**Comment by JonathanWenger** [comment]
I agree with the choice `black` with default settings.

**Comment by pnkraemer** [comment]
I don't mind as long as it doesn't rate my code like pylint does ;)

**Comment by nathanaelbosch** [comment]
> I don't mind as long as it doesn't rate my code like pylint does ;)

That I cannot guarantee!

**Comment by nathanaelbosch** [comment]
Update: My current approach and PR (#102) will not lead to automated code formatting.

The GitHub action (as described [here](https://github.com/psf/black#github-actions) does not automatically format code, but just checks if the formatting is correct. After thinking about it a bit, I believe that this is actually the better solution (in comparison to automated formatting):
- It motivates regular developers to actually set up *Black* themselves (through pre-commit or their IDE), which should improve the overall code quality since the developer is aware of the changes the formatting tool makes.
- It requires only little effort, for us or the new developer, to fix the (few) PRs in which the check for *Black* fails

**Comment by nathanaelbosch** [comment]
Closing since #150 adds pylint to our CI. The "docstring checker" part is open, but contained in #95.
