### ISSUE TITLE
Automatically check whether docstrings are complete and correctly formatted

### ISSUE THREAD

**Issue by JonathanWenger** [probabilistic-numerics/probnum#95]
~Use pytest, e.g. `pytest --doctest-glob='*.rst'. ` during the Travis build.~

Also look into `pydocstyle` and `darglint`. These check whether docstrings are complete and correctly formatted. Output looks like this:

```
backpack/core/derivatives/basederivatives.py:jac_t_mat_prod:63: DAR101: Missing parameter(s) in Docstring: - module
backpack/core/derivatives/basederivatives.py:jac_t_mat_prod:63: DAR101: Missing parameter(s) in Docstring: - g_inp
backpack/core/derivatives/basederivatives.py:jac_t_mat_prod:63: DAR101: Missing parameter(s) in Docstring: - g_out
backpack/core/derivatives/basederivatives.py:jac_t_mat_prod:63: DAR101: Missing parameter(s) in Docstring: - mat
backpack/core/derivatives/basederivatives.py:jac_t_mat_prod:63: DAR201: Missing "Returns" in Docstring: - return
backpack/core/derivatives/basederivatives.py:_jac_t_mat_prod:82: DAR101: Missing parameter(s) in Docstring: - module
backpack/core/derivatives/basederivatives.py:_jac_t_mat_prod:82: DAR101: Missing parameter(s) in Docstring: - g_inp
backpack/core/derivatives/basederivatives.py:_jac_t_mat_prod:82: DAR101: Missing parameter(s) in Docstring: - g_out
backpack/core/derivatives/basederivatives.py:_jac_t_mat_prod:82: DAR101: Missing parameter(s) in Docstring: - mat
backpack/core/derivatives/basederivatives.py:_jac_t_mat_prod:82: DAR401: Missing exception(s) in Raises section: -r NotImplementedError
```

_Originally posted by @JonathanWenger in https://github.com/probabilistic-numerics/probnum/issues/14#issuecomment-614483553_

**Comment by nathanaelbosch** [comment]
It should be easy to include running `pydocstyle` (or whatever tool we end up using) into tox, and thereby into Travis :) 

Less easy: Fixing all the errors that `pydocstyle` raises when I run it on the `development` branch :fearful:

**Comment by nathanaelbosch** [comment]
With the `pylint` PR merged (#150), I see the following points for improving the docstring situation:
1.  Write missing docstrings: `pyling src --enable="missing-module-docstring,missing-function-docstring"` should pass. 
2. Check for correct parameters, return values, exceptions, etc in docstrings:
    `pylint src --enable="pylint.extensions.docparams"` should pass. Could also be tackled step by step, by resolving one type of error after another. See also the [documentation](http://pylint.pycqa.org/en/latest/technical_reference/extensions.html#parameter-documentation-checker). It might also be useful to cross-check with [darglint](https://github.com/terrencepreilly/darglint).
3. Check for docstyle: `pylint src --enable="pylint.extensions.docstyle"`. This did not seem too strict.
4. The final goal would probably still be to use [pydocstyle](http://www.pydocstyle.org/en/5.0.1/), but this should probably be done *after* resolving the checks before this.

For all of these, the corresponding errors should be enabled in the `./pyproject.toml` after fixing them.

I think it would actually make sense to open separate issues for 1-3 since these tasks are well-defined and have a clear goal, and maybe keep 4 as the final task of this issue. @JonathanWenger what do you think?

**Comment by nathanaelbosch** [comment]
I just moved the first of these points (writing missing docstrings) to the per-module exceptions.
They are therefore now also tracked in #155, #156, #157, #158, #159, #160, #161, #162.

**Comment by JonathanWenger** [comment]
### Decision from the software meeting:
Add `pylint src --enable="pylint.extensions.docparams,pylint.extensions.docstyle"` to the tox configuration.

**Comment by JonathanWenger** [comment]
Also add [docformatter(https://github.com/myint/docformatter) to the recommended `pre-commit` configuration.
